name: Build Push and Deploy

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: nginx-demo

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Get Server Secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ secrets.VAULT_ADDR }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            devops/serpi-locallserver/server1 host | SERVER_HOST ;
            devops/serpi-locallserver/server1 username | SERVER_USER ;
            devops/serpi-locallserver/server1 password | SERVER_PASSWORD ;
            devops/serpi-locallserver/server1 port | SERVER_PORT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-demo:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-demo:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          password: ${{ env.SERVER_PASSWORD }}
          port: ${{ env.SERVER_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-demo:latest

            docker stop nginx-demo || true
            docker rm nginx-demo || true

            docker run -d \
              --name nginx-demo \
              --restart unless-stopped \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/nginx-demo:latest